###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: rabbitmqtest-mysql
      working_dir: /application
      volumes:
        - ./localstorage/mysql_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=codespy
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8302:3306"

    webserver:
      image: nginx:alpine
      container_name: rabbitmqtest-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8300:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: rabbitmqtest-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      environment:
        MYVAR: 'false'
        MYSECVAR: 'true'
        MYTHIRT: 'neen'
        PHP_IDE_CONFIG: "serverName=symfonytestdocker.docker"
        XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      env_file:
        - .env

    phpmyadmin:
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8303:80'
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: password

    rabbitmq:
      image: 'rabbitmq:3.6-management-alpine'
      ports:
        # The standard AMQP protocol port
        - '5672:5672'
        # HTTP management UI / guest/guest
        - '15672:15672'